// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CalendarStatus(): $CancellablePromise<$models.CalendarStatus> {
    return $Call.ByID(1427960982).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Chat(req: $models.ChatRequest): $CancellablePromise<$models.ChatResponse> {
    return $Call.ByID(3484087444, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ConnectGoogleCalendar(): $CancellablePromise<$models.CalendarStatus> {
    return $Call.ByID(1030111461).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(1687209814);
}

export function SetWindowMode(mode: string): $CancellablePromise<$models.WindowModeResponse> {
    return $Call.ByID(1023272237, mode).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CalendarStatus.createFrom;
const $$createType1 = $models.ChatResponse.createFrom;
const $$createType2 = $models.WindowModeResponse.createFrom;
