// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AssistantAction {
    "kind": string;
    "status": string;
    "title": string;
    "detail": string;
    "eventId": string;
    "link": string;
    "time": string;

    /** Creates a new AssistantAction instance. */
    constructor($$source: Partial<AssistantAction> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("eventId" in $$source)) {
            this["eventId"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssistantAction instance from a string or object.
     */
    static createFrom($$source: any = {}): AssistantAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssistantAction($$parsedSource as Partial<AssistantAction>);
    }
}

export class CalendarStatus {
    "connected": boolean;
    "message": string;
    "account": string;
    "error": string;

    /** Creates a new CalendarStatus instance. */
    constructor($$source: Partial<CalendarStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalendarStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CalendarStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalendarStatus($$parsedSource as Partial<CalendarStatus>);
    }
}

export class ChatMessage {
    "id": string;
    "role": string;
    "content": string;

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

export class ChatRequest {
    "prompt": string;
    "messages": ChatMessage[];

    /** Creates a new ChatRequest instance. */
    constructor($$source: Partial<ChatRequest> = {}) {
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatRequest {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        return new ChatRequest($$parsedSource as Partial<ChatRequest>);
    }
}

export class ChatResponse {
    "message": string;
    "actions": AssistantAction[];
    "error": string;

    /** Creates a new ChatResponse instance. */
    constructor($$source: Partial<ChatResponse> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatResponse {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField1_0($$parsedSource["actions"]);
        }
        return new ChatResponse($$parsedSource as Partial<ChatResponse>);
    }
}

export class WindowModeResponse {
    "mode": string;
    "width": number;
    "height": number;

    /** Creates a new WindowModeResponse instance. */
    constructor($$source: Partial<WindowModeResponse> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowModeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowModeResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowModeResponse($$parsedSource as Partial<WindowModeResponse>);
    }
}

// Private type creation functions
const $$createType0 = ChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = AssistantAction.createFrom;
const $$createType3 = $Create.Array($$createType2);
